version: "3.8"

services:
  db:
    image: postgres:15
    container_name: rental_booking_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: kanucast/lala-homes-be:latest
    container_name: rental_booking_api
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - "5000:5000"
    command: ["npm", "run", "start"]

volumes:
  postgres_data:
