name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
  
      DB_USER: ${{ secrets.TEST_DB_USER }}
      DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
      DB_NAME: ${{ secrets.TEST_DB_NAME }}
      DB_HOST: ${{ secrets.TEST_DB_HOST }}
      DB_PORT: 5432
      DB_SSL: "true"
      DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
      

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run migrations
        run: npx sequelize-cli db:migrate

      - name: Run tests
        run: npm test
